-- ============================================================
-- โครงสร้างสำหรับประเภทผู้ใช้ "สำนักงาน" (Office)
-- ยอดขายสำนักงานใช้ช่องทางกรอกไม่เหมือนสาขา (ไม่ใช้ Cash/Grab/Lineman ฯลฯ)
-- รันใน Supabase Dashboard → SQL Editor หลังสร้างตารางหลักแล้ว
-- ============================================================

-- 1) เพิ่มคอลัมน์ Role ในตาราง User (ถ้ายังไม่มี)
-- ค่า: 'branch' = สาขา, 'admin' = แอดมิน, 'office' = สำนักงาน
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'User' AND column_name = 'Role'
  ) THEN
    ALTER TABLE public."User" ADD COLUMN "Role" text NOT NULL DEFAULT 'branch';
  END IF;
END $$;

-- อัปเดต user ที่เป็นแอดมิน (ถ้าเดิมใช้ email มีคำว่า admin)
-- UPDATE public."User" SET "Role" = 'admin' WHERE LOWER("Email") LIKE '%admin%';

-- 2) ตารางยอดขายสำนักงาน (ช่องทางต่างจากสาขา — ปรับชื่อคอลัมน์ตามจริง)
-- ตัวอย่างช่องทาง: โครงการA, โครงการB, สัญญา, บริการ, อื่นๆ (แทน Cash/Grab/Lineman ฯลฯ)
CREATE TABLE IF NOT EXISTS public."OfficeSales" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Branch Code" text NOT NULL,
  "Date" date NOT NULL,
  "Channel1" numeric NOT NULL DEFAULT 0,
  "Channel2" numeric NOT NULL DEFAULT 0,
  "Channel3" numeric NOT NULL DEFAULT 0,
  "Other" numeric NOT NULL DEFAULT 0,
  "Total" numeric NOT NULL DEFAULT 0,
  "Notes" text,
  "CreatedBy" text,
  "CreatedAt" timestamp with time zone DEFAULT now(),
  "UpdatedAt" timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE public."OfficeSales" IS 'ยอดขายสำนักงาน — เปลี่ยนชื่อ Channel1, Channel2, Channel3 เป็นชื่อช่องทางจริง (เช่น ProjectA, Contract, Service) ตามที่ใช้';

CREATE INDEX IF NOT EXISTS idx_office_sales_branch_date ON public."OfficeSales" ("Branch Code", "Date");

-- RLS (ถ้าใช้)
-- ALTER TABLE public."OfficeSales" ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow anon OfficeSales" ON public."OfficeSales" FOR ALL TO anon USING (true) WITH CHECK (true);
