-- ============================================================
-- ตารางสำหรับงบกำไรขาดทุนประจำเดือน (Profit & Loss)
-- รันใน Supabase Dashboard → SQL Editor
-- ============================================================

-- 1) ตั้งค่าการคิด VAT 7% ต่อสาขา
CREATE TABLE IF NOT EXISTS public."PnlSettings" (
  "Branch Code" text NOT NULL PRIMARY KEY,
  "EnableVat7" boolean NOT NULL DEFAULT true,
  "UpdatedAt" timestamp with time zone DEFAULT now()
);

-- 2) บิล/ใบเสร็จจากส่วนกลาง (ยอดเบิกใช้วัตถุดิบส่วนกลาง)
CREATE TABLE IF NOT EXISTS public."CentralBills" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Branch Code" text NOT NULL,
  "BillNo" text,
  "BillDate" date NOT NULL,
  "Amount" numeric NOT NULL DEFAULT 0,
  "CreatedAt" timestamp with time zone DEFAULT now()
);

-- 3) ค่าใช้จ่ายดำเนินการ ต่อเดือน ต่อสาขา (แต่ละหมวดหนึ่งแถว)
CREATE TABLE IF NOT EXISTS public."OperatingExpenses" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Branch Code" text NOT NULL,
  "YearMonth" text NOT NULL,
  "Category" text NOT NULL,
  "Amount" numeric NOT NULL DEFAULT 0,
  "Notes" text,
  "CreatedAt" timestamp with time zone DEFAULT now(),
  "UpdatedAt" timestamp with time zone DEFAULT now(),
  UNIQUE("Branch Code", "YearMonth", "Category")
);

-- Index สำหรับ query ตามสาขาและเดือน
CREATE INDEX IF NOT EXISTS idx_central_bills_branch_date ON public."CentralBills" ("Branch Code", "BillDate");
CREATE INDEX IF NOT EXISTS idx_operating_expenses_branch_month ON public."OperatingExpenses" ("Branch Code", "YearMonth");

-- RLS (ถ้าใช้): อนุญาต anon อ่าน/เขียน
-- ALTER TABLE public."PnlSettings" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public."CentralBills" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public."OperatingExpenses" ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow anon PnlSettings" ON public."PnlSettings" FOR ALL TO anon USING (true) WITH CHECK (true);
-- CREATE POLICY "Allow anon CentralBills" ON public."CentralBills" FOR ALL TO anon USING (true) WITH CHECK (true);
-- CREATE POLICY "Allow anon OperatingExpenses" ON public."OperatingExpenses" FOR ALL TO anon USING (true) WITH CHECK (true);
