-- ============================================================
-- ตารางเก็บยอดขาย Office: แท็บ RANGSAN + แท็บ SAO
-- รันใน Supabase Dashboard → SQL Editor
-- หมายเหตุ: ถ้ามีตาราง OfficeSales แบบเก่า (Channel1/2/3) อยู่แล้ว ให้ backup ก่อน แล้วค่อยรัน
-- ============================================================

-- ลบตารางเก่า (ถ้าเป็นโครงเดิม Channel1, Channel2, Channel3)
-- DROP TABLE IF EXISTS public."OfficeSales";

CREATE TABLE IF NOT EXISTS public."OfficeSales" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Branch Code" text NOT NULL,
  "Date" date NOT NULL,
  -- ========== แท็บ RANGSAN ==========
  -- 1. ยอดขายหน้าร้าน (วัตถุดิบและอุปกรณ์)
  rangsan_store_cash numeric NOT NULL DEFAULT 0,
  rangsan_store_transfer numeric NOT NULL DEFAULT 0,
  -- 2. คอร์สอน
  rangsan_course_basic_barista numeric NOT NULL DEFAULT 0,
  rangsan_course_basic_latte_art numeric NOT NULL DEFAULT 0,
  rangsan_course_latte_art numeric NOT NULL DEFAULT 0,
  rangsan_course_other numeric NOT NULL DEFAULT 0,
  -- 3. เครื่องชง เครื่องบด
  rangsan_equip_brewer numeric NOT NULL DEFAULT 0,
  rangsan_equip_grinder numeric NOT NULL DEFAULT 0,
  rangsan_equip_set numeric NOT NULL DEFAULT 0,
  rangsan_equip_other numeric NOT NULL DEFAULT 0,
  -- 4. ยอดขายแฟรนไชส์
  rangsan_franchise_franchise numeric NOT NULL DEFAULT 0,
  rangsan_franchise_app numeric NOT NULL DEFAULT 0,
  rangsan_franchise_branch_buy numeric NOT NULL DEFAULT 0,
  -- 5. ออนไลน์
  rangsan_online_line numeric NOT NULL DEFAULT 0,
  rangsan_online_facebook numeric NOT NULL DEFAULT 0,
  rangsan_online_shopee numeric NOT NULL DEFAULT 0,
  rangsan_online_lazada numeric NOT NULL DEFAULT 0,
  rangsan_online_tiktok numeric NOT NULL DEFAULT 0,
  rangsan_online_other numeric NOT NULL DEFAULT 0,
  -- ========== แท็บ SAO ==========
  -- 1. การรีเทรนสาขา
  sao_retrain_fee numeric NOT NULL DEFAULT 0,
  sao_retrain_other numeric NOT NULL DEFAULT 0,
  -- 2. ยอดขายแฟรนไชส์ (SAO)
  sao_franchise_franchise numeric NOT NULL DEFAULT 0,
  sao_franchise_app numeric NOT NULL DEFAULT 0,
  sao_franchise_branch_buy numeric NOT NULL DEFAULT 0,
  -- 3. ออนไลน์ (SAO)
  sao_online_line numeric NOT NULL DEFAULT 0,
  sao_online_facebook numeric NOT NULL DEFAULT 0,
  sao_online_shopee numeric NOT NULL DEFAULT 0,
  sao_online_lazada numeric NOT NULL DEFAULT 0,
  sao_online_tiktok numeric NOT NULL DEFAULT 0,
  sao_online_other numeric NOT NULL DEFAULT 0,
  -- รวม (คำนวณได้จากฝั่งแอป หรือเก็บไว้สำหรับรายงาน)
  rangsan_total numeric NOT NULL DEFAULT 0,
  sao_total numeric NOT NULL DEFAULT 0,
  -- เมตาดาตา
  "Notes" text,
  "CreatedBy" text,
  "CreatedAt" timestamp with time zone DEFAULT now(),
  "UpdatedAt" timestamp with time zone DEFAULT now(),
  UNIQUE ("Branch Code", "Date")
);

COMMENT ON TABLE public."OfficeSales" IS 'ยอดขาย Office: แท็บ RANGSAN (หน้าร้าน, คอร์สอน, เครื่องชง/บด, แฟรนไชส์, ออนไลน์) + แท็บ SAO (รีเทรน, แฟรนไชส์ SAO, ออนไลน์ SAO)';

CREATE INDEX IF NOT EXISTS idx_office_sales_branch_date ON public."OfficeSales" ("Branch Code", "Date");

-- ถ้าใช้ RLS
-- ALTER TABLE public."OfficeSales" ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "OfficeSales policy" ON public."OfficeSales" FOR ALL USING (true) WITH CHECK (true);
